
FROM alpine:3.11.3 as kube
ARG KUBECTL_VERSION
RUN apk add wget \
  && wget -q https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl \
  && chmod +x /usr/local/bin/kubectl

FROM alpine:3.11.3 as helm
ARG HELM_VERSION
RUN apk add wget \
  && wget -q https://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm \
  && chmod +x /usr/local/bin/helm

FROM alpine:3.11.3 as authenticator
ARG AWS_IAM_AUTHENTICATOR_VERSION
RUN apk add wget \
  && wget -q https://amazon-eks.s3-us-west-2.amazonaws.com/${AWS_IAM_AUTHENTICATOR_VERSION}/bin/linux/amd64/aws-iam-authenticator -O /usr/local/bin/aws-iam-authenticator \
  && chmod +x /usr/local/bin/aws-iam-authenticator

FROM alpine:3.11.3 as argo
ARG ARGO_VERSION
RUN apk add wget \
  && wget -q https://github.com/argoproj/argo/releases/download/${ARGO_VERSION}/argo-linux-amd64 -O /usr/local/bin/argo \
  && chmod +x /usr/local/bin/argo

FROM alpine:3.11.3 as render
ARG RENDER_VERSION
RUN apk add curl \
  && curl -L -s https://github.com/VirtusLab/render/releases/download/${RENDER_VERSION}/render-linux-amd64 -o /usr/local/bin/render \
  && chmod +x /usr/local/bin/render

FROM landtech/ci-node:latest
COPY --from=kube /usr/local/bin/kubectl /usr/local/bin
COPY --from=helm /usr/local/bin/helm /usr/local/bin
COPY --from=authenticator /usr/local/bin/aws-iam-authenticator /usr/local/bin
COPY --from=argo /usr/local/bin/argo /usr/local/bin
COPY --from=render /usr/local/bin/render /usr/local/bin
COPY kubernetes/install_kube_iam_user.sh /usr/bin/install_kube_iam_user.sh

ENV SHELL /bin/bash

RUN apk update \
  && apk add --no-cache openssh \
  && pip install --upgrade yq \
  # init helm client
  && helm init --client-only \
  # kubectl aliases
  && curl --fail -s -o /usr/local/bin/k8_cluster_domain https://raw.githubusercontent.com/landtechnologies/reformation/master/assets/aliases/k8_cluster_domain \
  && chmod +x /usr/local/bin/k8_cluster_domain \
  && curl --fail -s -o /usr/local/bin/k8_cluster_name https://raw.githubusercontent.com/landtechnologies/reformation/master/assets/aliases/k8_cluster_name \
  && chmod +x /usr/local/bin/k8_cluster_name

