
FROM alpine:3.13.2 as kube
ARG KUBECTL_VERSION
RUN apk add wget \
  && wget -q https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -O /usr/local/bin/kubectl \
  && chmod +x /usr/local/bin/kubectl

FROM alpine:3.13.2 as helm
ARG HELM_VERSION
RUN apk add wget \
  && wget -q https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz -O - | tar -xzO linux-amd64/helm > /usr/local/bin/helm \
  && chmod +x /usr/local/bin/helm
RUN helm repo add stable "https://charts.helm.sh/stable"
RUN helm repo add bitnami "https://charts.bitnami.com/bitnami"

FROM alpine:3.13.2 as authenticator
ARG AWS_IAM_AUTHENTICATOR_VERSION
RUN apk add wget \
  && wget -q https://amazon-eks.s3-us-west-2.amazonaws.com/${AWS_IAM_AUTHENTICATOR_VERSION}/bin/linux/amd64/aws-iam-authenticator -O /usr/local/bin/aws-iam-authenticator \
  && chmod +x /usr/local/bin/aws-iam-authenticator

FROM alpine:3.13.2 as argo
ARG ARGO_VERSION
RUN apk add wget \
  && wget -q https://github.com/argoproj/argo/releases/download/${ARGO_VERSION}/argo-linux-amd64.gz -O - | gunzip -dc - > /usr/local/bin/argo \
  && chmod +x /usr/local/bin/argo

FROM alpine:3.13.2 as render
ARG RENDER_VERSION
RUN apk add curl \
  && curl -L -s https://github.com/VirtusLab/render/releases/download/${RENDER_VERSION}/render-linux-amd64 -o /usr/local/bin/render \
  && chmod +x /usr/local/bin/render

FROM alpine:3.13.2 as tilt
ARG TILT_VERSION
RUN apk add wget \
  && wget -q https://github.com/tilt-dev/tilt/releases/download/$TILT_VERSION/tilt.${TILT_VERSION//v}.linux.x86_64.tar.gz -O - | tar -xzO tilt > /usr/local/bin/tilt \
  && chmod +x /usr/local/bin/tilt


FROM dnanexus/promtool:2.9.2 as prometheus

FROM landtech/ci-node:latest
COPY --from=kube /usr/local/bin/kubectl /usr/local/bin
COPY --from=helm /usr/local/bin/helm /usr/local/bin
COPY --from=helm /root/.config/helm /root/.config/helm
COPY --from=authenticator /usr/local/bin/aws-iam-authenticator /usr/local/bin
COPY --from=argo /usr/local/bin/argo /usr/local/bin
COPY --from=render /usr/local/bin/render /usr/local/bin
COPY --from=tilt /usr/local/bin/tilt /usr/local/bin
COPY --from=prometheus /bin/promtool /usr/local/bin
COPY kubernetes/install_kube_iam_user.sh /usr/bin/install_kube_iam_user.sh

RUN helm repo update

RUN apk update \
  && apk add --no-cache openssh \
  # kubectl aliases
  && curl --fail -s -o /usr/local/bin/k8_cluster_domain https://raw.githubusercontent.com/landtechnologies/reformation/master/assets/bin/k8_cluster_domain \
  && chmod +x /usr/local/bin/k8_cluster_domain \
  && curl --fail -s -o /usr/local/bin/k8_cluster_name https://raw.githubusercontent.com/landtechnologies/reformation/master/assets/bin/k8_cluster_name \
  && chmod +x /usr/local/bin/k8_cluster_name

