FROM alpine:3.11.3

ARG VERSION
ENV SHELL /bin/bash

COPY shared/semver.sh /usr/local/bin
COPY shared/core_deps.sh .
RUN ./core_deps.sh \
    && rm core_deps.sh \
    && pip3 install awsebcli==$VERSION
