FROM node:14.15.5-alpine3.13

ENV PATH="./node_modules/.bin:${PATH}"
ENV SHELL /bin/bash

COPY shared/deployment shared/semver.sh /usr/local/bin/
COPY shared/core_deps.sh .

RUN ./core_deps.sh \
    && rm core_deps.sh \
    && apk add --no-cache \
        docker \
        yarn
